### ISSUE TITLE
Its wont stop even basic ads

### ISSUE THREAD

**Issue by parmeetmaster** [islamdidarmd/AdBlockerWebview#4]
Please check this project its stop block even single ads on dailymotion youtube etc

**Comment by didarul-codes** [comment]
Thank you for opening the issue. 
Can you please provide a minimal example to reproduce the issue?

**Comment by didarul-codes** [comment]
Closing the issue as there is no response. If it's possible to provide a minimal reproducible sample, feel free to re open the issue
